import { palette } from './palette';

export const logo = () => [
  {
    type: 'ellipse',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    x: 0,
    y: 240,
    strokeColor: palette.BLUE,
    backgroundColor: palette.BLUE,
    width: 217,
    height: 217,
  },
  {
    type: 'ellipse',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    x: 281,
    y: 240,
    strokeColor: palette.RED,
    backgroundColor: palette.RED,
    width: 217,
    height: 217,
  },
  {
    type: 'ellipse',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    x: 140,
    y: 0,
    strokeColor: palette.BLUE,
    backgroundColor: palette.BLUE,
    width: 217,
    height: 217,
  },
  {
    type: 'ellipse',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    x: 180,
    y: 63,
    strokeColor: palette.RED,
    backgroundColor: palette.RED,
    width: 137,
    height: 137,
  },
]
